### ISSUE TITLE
Editing the Sentence does not appear to work.

### ISSUE THREAD

**Issue by Hammr5900x** [keijiinouehotmail/OpenAIGPTAssistedColumnPCF#6]
I created a Sentence in the pcf control for "summarize in 500 words or less". I then expect the user to type in a website value at the end...resulting in the below response. E.g. summarize in 500 words or less https://www.microsoft.com 

"As an artificial intelligence language model, I do not have any context or information about what needs to be summarized. Therefore, I cannot provide a summary without additional information or guidance from you. Please provide me with more details on what information needs to be summarized and I will do my best to assist you."

Is it not possible to have the start of a sentence then allow the ser to modify it before sending it to ChatGPT?

**Comment by keijiinouehotmail** [comment]
In released versions, there is no ability for users to modify which Prompt will be sent to ChatGPT. It depends on what your administrator has already configured.
